version: '3.8'
services:
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network

  sandbox:
    build:
      context: .
      dockerfile: sandbox/Dockerfile
    networks:
      - app-network
    volumes:
      - .:/usr/src/app

networks:
  app-network:
    driver: bridge
